version: "3.7"

services:
    ss-server:
        image: acrisliu/shadowsocks-libev
        command:
            - "/start-server.sh"
        volumes:
            - ./scripts/start-server.sh:/start-server.sh:ro
        restart: on-failure
        env_file: .env

    nginx:
        container_name: ${NGINX_CONTAINER}
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
          - ./nginx/templates:/etc/nginx/templates:ro
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        restart: on-failure
        ports:
          - "443:443/tcp"
        env_file: .env
        ulimits:
          nofile:
            soft: 65535
            hard: 65535
        entrypoint: ["/docker-entrypoint.sh", "nginx"]
